### ISSUE TITLE
Get Valve Status on Demand

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/ADPL#41]
Get valve status on demand. Should we also publish this along with the other data periodically? @aforbis-stokes

**Comment by mlp6** [comment]
@aforbis-stokes can you comment on if this is desired?

**Comment by aforbis-stokes** [comment]
Sorry I missed this one. Yes, being able to check if the valve is open would be a good feature.

**Comment by mlp6** [comment]
and just to confirm, do you want this to be regularly reported back to the web server, or just make it accessible for on-demand query?

**Comment by aforbis-stokes** [comment]
I don't think it would look good on the graph, but I think if it were in the dashboard, it would be valuable information.

**Comment by mlp6** [comment]
We can/should add a "status light" on the dashboard; maybe a green circle for open, and red circle for closed?  This would just be for the active state at the time of last status update.

**Comment by suyashkumar** [comment]
Indeed, this is easy enough! do we have a Spark.variable() registered for valve status? Can someone point me to that declaration?

**Comment by mlp6** [comment]
The Valve class has a public `gasOn` boolean variable that could be easily published.  I'll add that hook now... would it be "easy" to only poll the status when refreshing the webpage instead of publishing it all the time?

**Comment by suyashkumar** [comment]
Perfect. I'll get this on demand, as that's what we want right? Or do we want to keep track of this information longitudinally (in which case can publish and make it avail on demand).

**Comment by mlp6** [comment]
I think it would just be an instantaneous check...

**Comment by suyashkumar** [comment]
Closed by 27107a1 (and cb39352)

**Comment by mlp6** [comment]
Looks like the web server might be crashing on a timeout error:

```
GET /api/gasOn/ADPLdukelab4601 304 1838.981 ms - -
GET /api/list/kenya-1 304 1283.297 ms - -
GET /api/gasOn/kenya-1 - - ms - -
{
  "error": "Timed out."
}
_http_outgoing.js:344
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/bitnami/ADPL/software/logging/node_modules/express/lib/response.js:718:10)
    at ServerResponse.json (/home/bitnami/ADPL/software/logging/node_modules/express/lib/response.js:246:10)
    at Request._callback (/home/bitnami/ADPL/software/logging/api/ondemand.js:14:8)
    at Request.self.callback (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/bitnami/ADPL/software/logging/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by suyashkumar** [comment]
Be should be good now, will push a new update
