### ISSUE TITLE
docker: js import error

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#67]
```
module.js:327
    throw err;
    ^

Error: Cannot find module './twilio_auth.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/src/api/message.js:8:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/src/config/routes.js:9:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

**Comment by suyashkumar** [comment]
@mlp6: twilio has auth keys in twilio_auth.js. Grab this from the current server.

**Comment by suyashkumar** [comment]
It's gitignored to hide the keys.
