### ISSUE TITLE
mongodb error: connection refused

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#68]
```
Listening on port 9000

/src/node_modules/mongoose/node_modules/mongodb/lib/server.js:242
        process.nextTick(function() { throw err; })
                                      ^
Error: connect ECONNREFUSED 127.0.0.1:27017
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

**Comment by suyashkumar** [comment]
MongoDB either isn't running or isn't installed (or isn't running on the right port)

**Comment by mlp6** [comment]
still not working... hmmm...
