### ISSUE TITLE
webserver issue

### ISSUE THREAD

**Issue by mlp6** [mlp6/ADPL#89]
``/boot`` was full on the VM, so I cleaned it up, upgraded packages and rebooted.  restarting the server yielded this error; insight?
```
[0] % ./start_adpl_server.sh
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:911:11)
    at exports._exceptionWithHostPort (util.js:934:20)
    at Server._listen2 (net.js:1248:14)
    at listen (net.js:1284:10)
    at Server.listen (net.js:1380:5)
    at Object.<anonymous> (/home/bitnami/ADPL/software/logging/server.js:44:10)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

**Comment by suyashkumar** [comment]
Just tried again and it worked! It seems that perhaps another instance of the server was running (perhaps in a screen?). Could this have happened because of an autostart script on boot? Usually when i get an address in use error I usually run `lsof -i:80` to see what processes are bound to port 80 :). Useful to debug! 

I'm happy to investigate this more as well if it crops up again!
